branches:
  only:
    - main
language: node_js
node_js:
- lts/*
git:
  depth: 30
install:
- yarn --frozen-lockfile
script:
- ./build.sh
cache: yarn
deploy:
- provider: npm
  email: gd4ark@gmail.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
